GET http://localhost:3000/players

###
POST http://localhost:3000/players
Content-Type: application/json

{
  "player_name": "Vishal",
  "jersey_number": 17,
  "role": "Bowler"
}

###
GET http://localhost:3000/players/:playerId

###
PUT http://localhost:3000/players/:playerId
Content-Type: application/json

{
  "player_name": "Maneesh",
  "jersey_number": 54,
  "role": "All-rounder"
}

###
DELETE http://localhost:3000/players/:playerId
